### PR TITLE
fixed menu position

### PR DESCRIPTION
**Pull request by rafaelcastrocouto**
menu is no longer cut in small height windows

### CODE REVIEW

**Comment by coderaiser** [comment]
Nice, thank you. It fixes issue with height, but would be better not to set `y` to `0`, but make calculation to put menu little bit lower to bottom when there is space for this (like it works in normal situation).
Also would be great to put menu to the left when same issue with width occurs.
Good issue to think about.

**Comment by coderaiser** [comment]
Merged as https://github.com/coderaiser/menu-io/commit/47426fff62c0b2a7d4996dee2baa51d26bee6996. Landed in [v1.0.0](https://github.com/coderaiser/menu-io/releases/tag/v1.0.0).

**Comment by rafaelcastrocouto** [comment]
The menu height returned by computed style was not considering the borders (it does not have box-sizing: border-box), and offsetHeight also has an overall better performance.

To make it as you want just change menu-io.js line 215 to:

```
    if (y < 0) {
          x += 14;
          y = (heightInner - heightMenu)/2;
    }
```

**Comment by coderaiser** [comment]
it's not quite what I had in mind, but anyway thank you, your solution is functional and now `menu-io` better then it was.

**Pull request closed without merging**
